---
title: "Class Materials"
description: |
     Materials for class will be added here throughout the term.
editor_options: 
  markdown: 
    wrap: 72
output: 
    distill::distill_article:
       toc: TRUE
creative_commons: CC BY
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Week 1: Introducing Git and GitHub

### Goals

**Create version-controlled directory for your future website!**

But also: 

-    Create GitHub account  
-    Install Git  
-    Introduce yourself to Git  
-    Create first repository and link to it in R/RStudio  

### Resources

We will rely heavily on [Happy Git and GitHub with
R](https://happygitwithr.com/), in particular chapters 4, 6, 7, 11, and
12

### Materials for class

[Week 01 slides](slides/week01_introduction_git_and_github.html)

## Week 2: Create a distill website

### Goals

**Create a personal website to showcase your work**

- Create distill website in version-controlled directory  
- Edit `_site.yml` to control website structure  
- Edit index.Rmd to add personal details with **postcard**  
- Change website appearance with a basic theme change  

### Resources

The **distill** website has great material for getting started: <https://rstudio.github.io/distill/>\
Tom Mock has a nice intro to **distill**
[here](https://themockup.blog/posts/2020-08-01-building-a-blog-with-distill/)\
Alison Hill's post on **postcards**
[here](https://alison.rbind.io/post/2020-12-22-postcards-distill/)  
The [distillery showcase](https://jhelvy.github.io/distillery/showcase.html) is great for inspiration and ideas on website design

### Materials for class

[Week 02 slides](slides/week02_distill_websites.html)

## Week 3: More on **distill** articles and deploy website

### Goals

Ultimately we will deploy our websites via GitHub Pages

But first:  

- Add more **distill** articles to the website  
- Create citation entry  
- Add `.bib` file for references  
- Practice with footnotes, asides, and appendices  
- Add drop down menus and links within website pages  

### Resources

The **distill** website has articles on [**distill** basics](https://rstudio.github.io/distill/basics.html) as well as [citations](https://rstudio.github.io/distill/citations.html)  
GitHub docs has an overview of publishing via GitHub Pages [here](https://docs.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)

### Materials for class

[Week 03 slides](slides/week03_distill_articles_deploy.html)  
Save [.bib example file](files/article1.bib)  

## Week 4: Intro to display tables with **gt**

### Goals

Make display tables for output documents (e.g., manuscripts, presentations) using the **gt** package. We're starting with the basics: controlling the table content, adding information to the table, changing the table look, and saving to different formats.

### Resources

Thomas Mock has made a [**gt** Cookbook](https://themockup.blog/static/gt-cookbook.html#Introduction) that goes through functions in great detail  
The **gt** package website has a nice [intro](https://gt.rstudio.com/articles/intro-creating-gt-tables.html).  
Thomas Mock wrote a [post](https://themockup.blog/posts/2020-09-04-10-table-rules-in-r/) based on the "Ten Guidelines to Better Tables" paper that recreates tables with **gt**  

### Materials for class

Make sure you have installed current versions of packages **gt** and **dplyr**

[Week 04 slides](slides/week04_gt_tables.html)  
Save [`week04_gt_basics.Rmd`](files/week04_gt_basics.Rmd) to run code during the session  

## Week 5: **gt** flair: colors, images, and themes

### Goals

We'll look at a few more advanced features of **gt**, including adding cell text and fill colors, adding images to tables, and highlighting values. We'll also take a look at how folks build themes for their tables.

### Resources

The **gt** Cookbook has a section on [colors](https://themockup.blog/static/gt-cookbook.html#Conditional_formatting)  
Liam Bailey walks through a more complex **gt** [table-making example](https://www.liamdbailey.com/post/making-beautiful-tables-with-gt/) with colors and images  
Thomas Mock's [Advanced Cookbook](https://themockup.blog/static/gt-cookbook-advanced.html) has examples of creating themes and adding elements like bar charts    
See Anthony Schmidt's post on a **gt** APA theme [here](https://www.anthonyschmidt.co/post/2020-06-03-making-apa-tables-with-gt/)  

### Materials for class

Make sure you have installed current versions of packages **gt**, **dplyr**, and **tidyr**

[Week 05 slides](slides/week05_gt_flair.html)  
Save [`week05_more_gt.Rmd`](files/week05_more_gt.Rmd) to run code during the session    

## Week 6: Writing functions in R

### Goals

**Gain understanding of and learn how to write basic functions in R**

We'll discuss the basic structure of functions and then practice giving inputs and making outputs. We spend some time looking through the code of existing R functions.

### Resources

For more on all aspects of functions, see the [Functions chapter](https://r4ds.had.co.nz/functions.html) in Wickham and Grolemund's *R for Data Science*  
[Rice and Lumley's presentation](http://faculty.washington.edu/kenrice/rintro/intro17sess09v2.pdf) on writing functions is a nice overview  
If you are ready to go further with functions see [Stephanie Kirmer's presentation](https://skirmer.github.io/presentations/functions_with_r.html#1)  

### Materials for class

[Week 06 slides](slides/week06_writing_functions.html)  
Save [`week06_functions.Rmd`](files/week06_functions.Rmd) to run code during the session    

## Week 7: More Git and GitHub

### Goals

**Practice working with version-controlled projects with Git, specifically focusing on tools for collaboration.**

We will

- Review the README file    
- Add collaborators on GitHub      
- Solve a merge conflict with GitKraken  
- Learn to do a basic pull request using helper functions from package **usethis**  

### Resources

GitHub articles on [adding collaborators](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository) and [README files](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-readmes)  
Brief [article](https://blog.axosoft.com/merge-conflict-tool/) from GitKraken on their merge conflict tool  
Package **usethis** [article](https://usethis.r-lib.org/articles/articles/pr-functions.html) on pull request helpers  
A lecture in the [R programming for biologists class](https://r-bio.github.io/intro-git-rstudio/#pull-requests) outlines the basic approach to pull requests *without* **usethis**  

### Materials for class

Install [GitKraken](https://www.gitkraken.com/) on your computer. Also make sure you have a current version of packages **usethis** and **gh** installed.

[Week 07 slides](slides/week07_more_git.html)

## Week 8: Using interactive elements in HTML documents

### Goals

This week we will explore a handful of packages based on **htmlwidgets** for adding interactive elements to static HTML documents. We will finish with an example of adding interactive elements to a basic dashboard with **flexdashboard**. 

We will

- Use **plotly** to add interactivity to plots made with **ggplot2**  
- Use **DT** to allow for users to interact with a dataset  
- Look at **leaflet** for interactive maps  
- Use **dygraphs** to make interactive plots of time series data  
- Add interactive elements from packages above to a dashboard made with **flexdashboard**  

### Resources

[Intro to **htmlwidgets**](https://www.htmlwidgets.org/)  
[Using **plotly** from R](https://plotly.com/r/)  
[Interactive R data objects with **DT**](https://rstudio.github.io/DT/)  
[Interactive maps with **leaflet**](https://rstudio.github.io/leaflet/)  
[Charting time series data in R with **dygraphs**](https://rstudio.github.io/dygraphs/)  
[Interactive dashboards in R with **flexdashboard**](https://rmarkdown.rstudio.com/flexdashboard/)  

### Materials for class

We are exploring a variety of packages this week. Make sure you have current versions of: **htmlwidgets**, **palmerpenguins**, **ggplot2**, **plotly**, **DT**, **leaflet**, **dygraphs**, **flexdashboard**

[Week 08 slides](slides/week08_interactive_elements.html)  
Save [`week08_interaction.Rmd`](files/week08_interaction.Rmd) to knit to HTML output during the session  

## Week 9: Reproducible examples with **reprex**  

### Goals

The ultimate goal this week is to understand how to make a reproducible example or *reprex* when asking a question or reporting an issue. We'll discuss the elements of a reprex while working through a practice example and then use package **reprex** to create pasteable code and output.

### Resources

[Intro article](https://reprex.tidyverse.org/) and [Reprex do's and don'ts](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) from the **reprex** website    
Sharla Gelfand's "make a reprex... please" [slides](https://make-a-reprex-please.netlify.app/#1) and [recording](https://t.co/860RTqMvjy)   
[How to Datapasta](https://milesmcbain.github.io/datapasta/articles/how-to-datapasta.html)  
[RStudio Community guide](https://community.rstudio.com/t/faq-how-to-do-a-minimal-reproducible-example-reprex-for-beginners/23061)  
[Stack Overflow canonical thread](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)  
[Tidyverse help guide](https://www.tidyverse.org/help/)  

### Materials for class

We will be practice making reproducible examples with package **reprex**. Makes sure you have the current versions of **reprex** and **datapasta** installed.

[Week 09 slides](slides/week09_reprex.html) 

## Week 10: GitHub issues

### Goals

We will discuss the etiquette of reporting an issue for R packages on GitHub, then practice making an issue using **reprex** for the code and output.

### Resources

See Yihui Xie's [GitHub issue guide](https://yihui.org/issue/). This guide is specific to repositories he maintains but contains good general advice.  

### Materials for class

We will practice making reproducible examples with package **reprex**. Makes sure you have the current version of **reprex** installed.

[Week 10 slides](slides/week10_issues.html)
